### PR TITLE
Add ability to customize internal HttpClient

### PR DESCRIPTION
**Pull request by Arcalise08**
In a situation personally in which I need to directly modify the HttpClient being used in this library. So I added the ability to pass in an HttpClient to the UI options, which is used for the lifetime of the application.

### CODE REVIEW

**Comment by Burgyn** [comment]
Hey, 

thanks for the PR. The idea is good for me, but I don't like the implementation. I don't want to allow the `HttpClient` to be entered directly _(not good practice)_. I'd rather just add the `ClientName` and let the factory create the correct client based on that.

**Comment by Arcalise08** [comment]
I have made the requested changes. I accidently pushed a version change with this which we can rollback if you like. I also noticed that this package doesnt include `<GenerateDocumentationFile>true</GenerateDocumentationFile>` . I wasnt sure if that was something you had set locally as i cant get comments to show up once packed without it. But other then that I hope this meets your expectations.

**Comment by Arcalise08** [comment]
Sorry about the extra commits. I really shouldnt push changes before my morning coffee

**Comment by Burgyn** [comment]
Thanks a lot.

Your changes will be release soon as version `6.1.0` .

**Comment by Burgyn** [comment]
Sorry, `6.2.0` of course.

**Pull request merged**
