### PR TITLE
Bugfix/host path invalid

### LINKED ISSUE #44: Base path property incorrect value
**Describe the bug**
If gateway has no base path and service has base path swagger UI creates invalid urls for queries to gateway (with service base path)

### PR DESCRIPTION
**Pull request by jkosters**
I think this fixed #44 HttpRequest.Host does not contain Request scheme (see new unit test)

### CODE REVIEW

**Comment by Burgyn** [comment]
Hi, sorry but this PR is strange. It's look like combination of your previous PR.

Can you check it?

**Comment by jkosters** [comment]
You're right i messed up. I'll fix it.

**Comment by jkosters** [comment]
Done.

**Comment by Burgyn** [comment]
Hi, thanks for your efforts.
I'm merge this PR.

Your changes will be released as `v1.9.0`.

**Pull request merged**
